version: '3.8'
services:
  nginx:
    image: fps-all-on-one:latest
    restart: 'always'
    container_name: aio
    environment:
      - "TZ=Europe/Budapest"
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"

  database:
    image: mariadb
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql/"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app

volumes:
  uploads:
  db:
