version: '3'

services:
  database:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./var/mysql_data:/var/lib/mysql:delegated
      - ./var/mysql_log:/var/log/mysql:delegated
    ports:
      - "53306:3306"

  web:
    image: fps-web-php
    volumes:
      - ./:/www:delegated
    environment:
      - "TZ=Europe/Budapest"
    depends_on:
      - database
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
