version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_ROOT_HOST=%
    volumes:
      - ./var/mysql_data:/var/lib/mysql:delegated
      - ./var/mysql_log:/var/log/mysql:delegated
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - dev

  traefik:
    image: "traefik:v2.5"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=${USE_SWARM}"
      - "--providers.docker.exposedbydefault=false"
      - '--providers.docker.defaultRule=Host(`{{ index .Labels "traefik.subdomain" }}.${DOMAIN_SUFFIX}`)'
      - "--entrypoints.web.address=:80"
      #- "--entrypoints.web-secure.address=:443"
    ports:
      - "${PORT_HTTP}:80"
      - "${PORT_HTTPS}:443"
      - "${PORT_MANAGEMENT}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    networks:
      - dev

  phpmyadmin:
    image: "phpmyadmin"
    labels:
      - "traefik.enable=true"
      - "traefik.subdomain=phpmyadmin"
    environment:
      - PMA_ARBITRARY=1
      #- PMA_HOST=db
      #- PMA_USER=root
      #- PMA_PASSWORD=${DATABASE_ROOT_PASSWORD}
    expose:
      - 80
    networks:
      - dev
    links:
      - db



networks:
  dev: { name: dev }
