up:
	docker-compose up -d

stop:
	docker-compose stop

down:
	docker-compose down

logs:
	docker-compose logs -f

configure-standalone:
	docker network create dev

deconfigure-standalone:
	docker network remove dev || true
