version: '3'

services:
  web:
    image: b4zs/fps-web-php
    volumes:
      - ./web:/www:delegated
    environment:
      - "TZ=Europe/Budapest"
    expose: [80]
    labels:
      - "traefik.enable=true"
      - "traefik.subdomain=demo"
    networks:
      - dev_database
      - dev_proxy

networks:
  dev_database:
    external: true
  dev_proxy:
    external: true
