version: '3'

services:
  web:
    image: b4zs/fps-web:php8.0-node12
    volumes:
      - ./web:/www:delegated
      - ${CACHE_ROOT}/.composer:/root/.composer
      - ${CACHE_ROOT}/.npm:/root/.npm
    environment:
      - "TZ=Europe/Budapest"
    labels:
      - "traefik.enable=true"
      - "traefik.subdomain=demo"
      #- "traefik.http.routers.web-demo-project.tls=true"
    networks:
      - dev

networks:
  dev:
    external: true
